name: Release

on:
  #  push:
  #    tags:
  #      - 'v*'
#  push:
#    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'oracle'
          java-package: jdk
          cache: 'gradle'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_internal_config
        with:
          config: ${{ github.workspace }}/src/main/resources/internal.yaml

      - name: Get version
        id: get_version
        run: |
          echo VERSION: ${{ steps.read_internal_config.outputs['agentVersionName'] }}
          echo ::set-output name=VERSION::${{ steps.read_internal_config.outputs['agentVersionName'] }}
      #      - name: Get version
      #        id: get_version
      #        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: "Build Jar Archive with Gradle"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: ./gradlew clean -x test packageJarZipArchive

      - name: "Build Jpackage Archive with Gradle"
        run: ./gradlew --debug clean -x test packageJpackageZipArchive

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.get_version.outputs.VERSION }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          draft: true
          #          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          files: |
            releases/GTransAgent-bin-${{ steps.get_version.outputs.VERSION }}-jar.zip
            releases/GTransAgent-bin-${{ steps.get_version.outputs.VERSION }}-win-x86-64.zip
            releases/GTransAgent-bin-${{ steps.get_version.outputs.VERSION }}-linux-x86-64.zip
            releases/GTransAgent-bin-${{ steps.get_version.outputs.VERSION }}-linux-aarch64.zip
 
